@host = https://localhost:7292

POST {{host}}/api/authentication/register
Content-Type: application/json

{
  "firstName": "Hao",
  "lastName": "Nguyen",
  "email":"nguyendinhhao.it@gmail.com",
  "password":"123456"
}
